version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    db: # The name of the service
      container_name: postgres # Container name
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: qwerty@1
      ports:
        - '5432:5432' # Port mapping

    backend:
      container_name: backend
      build: 
        context: ./Backend # Location of our Dockerfile
      ports:
        - 5000:80
      depends_on:
        - db


    frontend:
      container_name: frontend 
      build: ./Frontend
      volumes: # Volume binding
        - './Frontend:/usr/src/app' 
      ports: 
        - '80:80'
      depends_on:
        - backend

    python-microservice:
      container_name: pyms
      build:
        context: ./pythonPutter
      depends_on:
        - backend